In [4]:
import numpy as np
a = np.array([2, 3, 4])
a
a.dtype
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

numpy.ndarray

In [ ]:
a = np.arange(6)                    # 1d array
print(a)           
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [1]:
import numpy as np

# 1D array
arr1D = np.arange(1, 11)   # [1,2,3,...,10] - 5 se 11 kiya kyuki 1 se 10 tak 10 elements hote hain
print("1D Array:", arr1D)

# --- Indexing & Slicing ---
print("Indexing arr1D[2]:", arr1D[2])        # 3rd element
print("Slicing arr1D[2:7]:", arr1D[2:7])    # elements from index 2 to 6

# --- Convert 1D to 2D ---
arr2D = arr1D.reshape(2, 5)   # 2 rows, 5 columns (10 elements)
print("\nConverted 2D Array:\n", arr2D)

# --- Access element in 2D ---
print("Element at [1,3]:", arr2D[1, 3])   # row=1, col=3

# --- Replace element in 2D ---
arr2D[1, 3] = 99
print("After replacing element at [1,3]:\n", arr2D)

# --- Convert 1D to 3D (shape 5x7) ---
arr1D_large = np.arange(1, 36)   # 35 elements (1 se 35 tak)
arr3D = arr1D_large.reshape(5, 7, 1)   # 5x7 matrix with depth=1 (5*7*1=35)
print("\nConverted 3D Array (5x7x1):\n", arr3D)

# --- Indexing in 3D ---
print("Element at [2,4,0]:", arr3D[2, 4, 0])   # row=2, col=4, depth=0

# --- Convert 3D back to 1D ---
arr1D_back = arr3D.flatten()
print("\nConverted back to 1D:\n", arr1D_back)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
Indexing arr1D[2]: 3
Slicing arr1D[2:7]: [3 4 5 6 7]

Converted 2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Element at [1,3]: 9
After replacing element at [1,3]:
 [[ 1  2  3  4  5]
 [ 6  7  8 99 10]]

Converted 3D Array (5x7x1):
 [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]]

 [[22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]]

 [[29]
  [30]
  [31]
  [32]
  [33]
  [34]
  [35]]]
Element at [2,4,0]: 19

Converted back to 1D:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
import numpy as np

# 1D array
arr1D = np.arange(1, 6)   # [1,2,3,...,10]
print("1D Array:", arr1D)

1D Array: [1 2 3 4 5]


In [4]:
# --- Indexing in 3D ---
print("Element at [2,4,0]:", arr3D[2, 4, 0])   # row=2, col=4, depth=0

Element at [2,4,0]: 19


In [2]:
a = np.arange(6)                    # 1d array
print(a)

b = np.arange(12).reshape(4, 3)     # 2d array
print( b)

c = np.arange(24).reshape( 2,3,4)     # 3d array
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
c [1:2:2] # slicing


array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
# --- Indexing in 3D ---
print("Element at [2,4,0]:", arr3D[2, 4, 0])   # row=2, col=4, depth=0

Element at [2,4,0]: 19


In [20]:
# --- Convert 1D to 3D (shape 5x7) ---
arr1D_large = np.arange(1, 36)   # 35 elements
arr3D = arr1D_large.reshape(5, 7, 1)   # 5x7 matrix with depth=1
print("\nConverted 3D Array (5x7x1):", arr3D)


Converted 3D Array (5x7x1): [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]]

 [[22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]]

 [[29]
  [30]
  [31]
  [32]
  [33]
  [34]
  [35]]]
