## Week 3 – NumPy and Pandas Assignments & Quizzes

### ASSIGNMENT 2: NumPy Array Math Wizard

In [2]:
# Demonstrate broadcasting and universal functions

# Step 1: Import NumPy as np
import numpy as np

print("=" * 60)
print("NUMPY ARRAY MATH WIZARD")
print("=" * 60)


# Step 2: Create arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

print("\n--- Initial Arrays ---")
print(f"arr1 (2x3):\n{arr1}")
print(f"arr2 (1D): {arr2}")



# Step 3: Perform arithmetic operations (demonstrating broadcasting)
print("\n--- Broadcasting Operations ---")


# Explanation of broadcasting (Step 4)
""""
BROADCASTING EXPLANATION:

Broadcasting allows NumPy to perform operations on arrays of different shapes.
Here, arr2 (shape 3,) is automatically stretched to match arr1 (shape 2,3):
- arr2 becomes effectively [[10,20,30], [10,20,30]] for the operation
- This happens without creating actual copies, making it memory efficient
- Rules: Dimensions are compared from right to left, and are compatible if:
  1. They are equal, or
  2. One of them is 1, or
  3. One dimension is missing
"""

# Addition
result_add = arr1 + arr2
print(f"\nAddition (arr1 + arr2):\n{result_add}")

# Subtraction
result_sub = arr1 - arr2
print(f"\nSubtraction (arr1 - arr2):\n{result_sub}")

# Multiplication
result_mul = arr1 * arr2
print(f"\nMultiplication (arr1 * arr2):\n{result_mul}")

# Division
result_div = arr1 / arr2
print(f"\nDivision (arr1 / arr2):\n{result_div}")



# Step 5: Create arr3 and apply universal functions
arr3 = np.array([1, 4, 9, 16, 25])
print("\n" + "=" * 60)
print("UNIVERSAL FUNCTIONS (ufuncs)")
print("=" * 60)
print(f"\narr3: {arr3}")

# Apply np.sqrt() - square root
sqrt_result = np.sqrt(arr3)
print(f"\nnp.sqrt(arr3): {sqrt_result}")

# Apply np.exp() - exponential (e^x)
exp_result = np.exp(arr3)
print(f"np.exp(arr3): {exp_result}")

# Apply np.sin() - sine (in radians)
sin_result = np.sin(arr3)
print(f"np.sin(arr3): {sin_result}")



# Step 6: Create arr4 and demonstrate aggregation functions
arr4 = np.array([[5, 12, 3], [8, 2, 7]])
print("\n" + "=" * 60)
print("AGGREGATION OPERATIONS")
print("=" * 60)
print(f"\narr4:\n{arr4}")

# Sum of all elements
total_sum = np.sum(arr4)
print(f"\nSum of all elements: {total_sum}")

# Max in each column (axis=0 means operate along rows, i.e., down each column)
max_per_column = np.max(arr4, axis=0)
print(f"Max in each column: {max_per_column}")

# Min in each row (axis=1 means operate along columns, i.e., across each row)
min_per_row = np.min(arr4, axis=1)
print(f"Min in each row: {min_per_row}")

# Additional aggregation examples
print(f"\nMean of all elements: {np.mean(arr4):.2f}")
print(f"Standard deviation: {np.std(arr4):.2f}")
print(f"Sum of each row: {np.sum(arr4, axis=1)}")
print(f"Sum of each column: {np.sum(arr4, axis=0)}")



# Step 7: Convert arr1 to float using type casting
print("\n" + "=" * 60)
print("TYPE CASTING")
print("=" * 60)

print(f"\nOriginal arr1 data type: {arr1.dtype}")
print(f"Original arr1:\n{arr1}")

# Method 1: Using astype()
arr1_float = arr1.astype(float)
print(f"\nAfter conversion (astype(float)):")
print(f"New data type: {arr1_float.dtype}")
print(f"arr1 as float:\n{arr1_float}")


# Demonstrate operations with float array
print(f"\nFloat array operations:")
print(f"Square root of float arr1:\n{np.sqrt(arr1_float)}")

print("\n" + "=" * 60)
print("END OF DEMONSTRATION")
print("=" * 60)

NUMPY ARRAY MATH WIZARD

--- Initial Arrays ---
arr1 (2x3):
[[1 2 3]
 [4 5 6]]
arr2 (1D): [10 20 30]

--- Broadcasting Operations ---

Addition (arr1 + arr2):
[[11 22 33]
 [14 25 36]]

Subtraction (arr1 - arr2):
[[ -9 -18 -27]
 [ -6 -15 -24]]

Multiplication (arr1 * arr2):
[[ 10  40  90]
 [ 40 100 180]]

Division (arr1 / arr2):
[[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]

UNIVERSAL FUNCTIONS (ufuncs)

arr3: [ 1  4  9 16 25]

np.sqrt(arr3): [1. 2. 3. 4. 5.]
np.exp(arr3): [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
np.sin(arr3): [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

AGGREGATION OPERATIONS

arr4:
[[ 5 12  3]
 [ 8  2  7]]

Sum of all elements: 37
Max in each column: [ 8 12  7]
Min in each row: [3 2]

Mean of all elements: 6.17
Standard deviation: 3.34
Sum of each row: [20 17]
Sum of each column: [13 14 10]

TYPE CASTING

Original arr1 data type: int64
Original arr1:
[[1 2 3]
 [4 5 6]]

After conversion (astype(float)):
New data type: floa