## Week 3 – NumPy and Pandas Assignments & Quizzes

## ASSIGNMENT 1: NumPy Array Explorer

In [3]:
## Demonstrate NumPy array creation methods and basic operations

# Step 1: Import NumPy as np
import numpy as np



# Step 2: Create the following arrays
Array_A = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])      # Array A: 1D array from list [2,4,6,8,10,12,14,16,18,20]


Array_B = np.zeros((3, 3))         # Array B: 3x3 array of zeros


Array_C = np.random.randint(1, 101, size=5)     # Array C: 5 random integers between 1 and 100


Array_D = np.linspace(0, 5, 10)     # Array D: 10 evenly spaced numbers between 0 and 5 using np.linspace()

# Print all created arrays
print("=" * 50)     
print("NUMPY ARRAY EXPLORER")
print("=" * 50)

print("\n--- Created Arrays ---")
print(f"Array A (1D from list): {Array_A}")
print(f"Array B (3x3 zeros):\n{Array_B}")
print(f"Array C (5 random ints 1-100): {Array_C}")
print(f"Array D (10 evenly spaced 0-5): {Array_D}")



# Step 3: For Array A print properties
print("\n--- Array A Properties ---")
print(f"Shape: {Array_A.shape}")
print(f"Data type: {Array_A.dtype}")
print(f"Size: {Array_A.size}")
print(f"Number of dimensions: {Array_A.ndim}")



# Step 4: Perform operations on Array A
print("\n--- Operations on Array A ---")
# Reshape to 2x5
Array_A_reshaped = Array_A.reshape(2, 5)
print(f"Reshaped to 2x5:\n{Array_A_reshaped}")

# Find max value and index
max_value = np.max(Array_A)
max_index = np.argmax(Array_A)
print(f"Max value: {max_value} at index {max_index}")

# Find min value and index
min_value = np.min(Array_A)
min_index = np.argmin(Array_A)
print(f"Min value: {min_value} at index {min_index}")



# Step 5: Create Array E and access specific element
Array_E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n--- Array E ---")
print(f"Array E:\n{Array_E}")
# Print element at row 1, column 2 (remember indexing starts at 0)
element = Array_E[1, 2]  # Row 1 (second row), Column 2 (third column)
print(f"Element at row 1, column 2: {element}")  # Should be 6

# Additional demonstration of array operations
print("\n--- Additional Operations ---")
print(f"Sum of all elements in Array A: {np.sum(Array_A)}")
print(f"Mean of Array A: {np.mean(Array_A)}")
print(f"Standard deviation of Array A: {np.std(Array_A):.2f}")
print(f"Array A multiplied by 2: {Array_A * 2}")

print("\n" + "=" * 50)

NUMPY ARRAY EXPLORER

--- Created Arrays ---
Array A (1D from list): [ 2  4  6  8 10 12 14 16 18 20]
Array B (3x3 zeros):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array C (5 random ints 1-100): [76 39 45 38  2]
Array D (10 evenly spaced 0-5): [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

--- Array A Properties ---
Shape: (10,)
Data type: int64
Size: 10
Number of dimensions: 1

--- Operations on Array A ---
Reshaped to 2x5:
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max value: 20 at index 9
Min value: 2 at index 0

--- Array E ---
Array E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6

--- Additional Operations ---
Sum of all elements in Array A: 110
Mean of Array A: 11.0
Standard deviation of Array A: 5.74
Array A multiplied by 2: [ 4  8 12 16 20 24 28 32 36 40]

